scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "router"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    static_configs:
      - targets: ["router:8000"]
  - job_name: "metrics-collector"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    static_configs:
      - targets: ["metrics:8000"]
