name: Feature Branch

on:
  push:
    branches-ignore:
      - prod

jobs:
  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make all
      - run: bash ops/build-report.sh
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push

  utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-utils

  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-contracts

  protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-protocol

  engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-engine

  server-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-server-node

  browser-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-browser-node

  router:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-router

  messaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make messaging
      - run: make start-messaging
      - run: make test-messaging
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 messaging_auth

  duet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make duet
      - run: make start-duet
      - run: make test-duet
      - name: Print logs
        if: failure()
        run: |
          docker service logs --tail 200 duet_alice
          docker service logs --tail 200 duet_bob

  trio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make trio
      - run: make start-trio
      - run: make test-trio
      - name: Print logs
        if: failure()
        run: |
          docker service logs --tail 200 trio_roger
          docker service logs --tail 200 trio_router
          docker service logs --tail 200 trio_carol
          docker service logs --tail 200 trio_dave

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make node
      - run: make start-node
      - run: make test-node
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 node_node

  routing-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make router
      - run: make start-router
      - run: make test-routing-node
      - name: Print logs
        if: failure()
        run: |
          docker service logs --tail 200 router_node
          docker service logs --tail 200 router_router

  messaging-prod:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - run: make pull
      - run: jq '.production = true' ops/config/messaging.default.json > messaging.config.json
      - run: make restart-messaging
      - run: bash ops/test-integration.sh messaging
      - name: Print logs
        if: failure()
        run: docker service ls && docker service logs --tail 200 messaging_auth

  routing-node-prod:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - run: make pull
      - run: jq '.production = true' ops/config/messaging.default.json > messaging.config.json
      - run: jq '.production = true' ops/config/router.default.json > router.config.json
      - run: make restart-router
      - run: bash ops/test-integration.sh router
      - name: Print logs
        if: failure()
        run: docker service ls && docker service logs --tail 200 router_node && docker service logs --tail 200 router_router
